export const State = {
  Harvest: 'Harvest',
  Pick: 'Pick',
  Build: 'Build',
  Repair: 'Repair',
  Withdraw: 'Withdraw',
  Upgrade: 'Upgrade',
  TransferToSpawn: 'TransferToSpawn',
  TransferToTower: 'TransferToTower',
  TransferToStorage: 'TransferToStorage',
  TransferToLink: 'TransferToLink',
  TransferToTerminal: 'TransferToTerminal',
  TransferToFactory: 'TransferToFactory',
  TransferToLab: 'TransferToLab',
  TransferToPowerSpawn: 'TransferToPowerSpawn',
  TransferToNuker: 'TransferToNuker',
  MoveTo: 'MoveTo',
  Back: 'Back',
  Boost: 'Boost',
  Unboost: 'Unboost',
  TransferToControllerContainer: 'TransferToControllerContainer',
}

